name       : libthai
version    : 0.1.28
release    : 1
source     :
    - https://linux.thai.net/pub/thailinux/software/libthai/libthai-0.1.28.tar.xz : ffe0a17b4b5aa11b153c15986800eca19f6c93a4025ffa5cf2cab2dcdf1ae911
license    : LGPL-2.1-only
component  : desktop.library
summary    : Thai language support routines
description: |
    A set of Thai language support routines aimed to ease developers' tasks to incorporate Thai language support in their applications.
setup      : |
    %configure --disable-static
builddeps  :
    - pkgconfig(datrie-0.2)
build      : |
    %make
install    : |
    %make_install
